services:
  server:
    build: .
    command:
      - run
      - -c
      - config.yaml
    working_dir: /app
    cap_add:
      - NET_ADMIN
    environment:
      RUST_LOG: 'info'
    volumes:
      - ./testdata/capybara.yaml:/app/config.yaml
    ports:
      - 15006:15006/tcp
    networks:
      - local

networks:
  local:
    external: false
