services:
  server:
    build: .
    image: ghcr.io/jjeffcaii/capybara:master
    command:
      - run
      - -c
      - capybara.yaml
    working_dir: /app
    cap_add:
      - NET_ADMIN
    environment:
      RUST_LOG: 'info'
    volumes:
      - ./testdata/capybara.docker.yaml:/app/capybara.yaml
      - ./testdata/config.yaml:/app/config.yaml
    ports:
      - "15006:15006/tcp"
    networks:
      - local

networks:
  local:
    external: false
