[package]
name = "capybara-util"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
log = "0.4"
pretty_env_logger = "0.5"

[dependencies]
once_cell = "1"
foreign-types = "0.5"
libc = "0.2"
anyhow = "1"
