[package]
name = "capybara-etc"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
pretty_env_logger = "0.5.0"

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
